### PR TITLE
chore: update submodules for log limit

### PR DESCRIPTION
**Pull request by aaron-steinfeld**
https://github.com/hypertrace/hypertrace-core-graphql/pull/66

### CODE REVIEW

**Comment by skjindal93** [comment]
I see @kotharironak already has a submodule PR up https://github.com/hypertrace/hypertrace-graphql/pull/89

**Comment by aaron-steinfeld** [comment]
"already" 🙄 just because no one would review this!

**Comment by skjindal93** [comment]
Whoops. Emails orderded by time

**Comment by kotharironak** [comment]
Ah!! I didn't see this one.

**Pull request closed without merging**
